### ISSUE TITLE
Doesn't play well with Coveralls on Travis

### ISSUE THREAD

**Issue by monfresh** [Fingertips/WAD#13]
Hi Manfred. Thanks a lot for this script. It works great, but for some reason, Coveralls tries to analyze files outside the app, like gems, and therefore causes coverage to decrease to about 50%. You can see the reports here: https://coveralls.io/r/codeforamerica/ohana-web-search

This only happens if I run `bin/wad` on Travis. If I just run the tests on Travis the regular way, coverage is at the normal percentage.

Do you have any idea what would be causing this and how to fix it?

Thanks!

**Comment by monfresh** [comment]
Figured it out. I had to exclude the `.bundle` directory, like this:

``` ruby
require 'coveralls'
Coveralls.wear!('rails')

SimpleCov.start do
  add_filter '.bundle'
end
```

**Comment by Manfred** [comment]
Great!
