### ISSUE TITLE
[BUG FIX] Fix the WAD script url in README

### ISSUE THREAD

**Issue by nomadslim** [Fingertips/WAD#14]
🐛 The url to get the wad script in the `README.md` seem to be incorrect.
I think the following command is correct : 

``` bash
### Get the WAD script
...
$ curl -o bin/wad https://raw.githubusercontent.com/Fingertips/WAD/master/bin/wad
```

Here as well

``` bash
### Alternative build configuration
...
install: "curl https://raw.githubusercontent.com/Fingertips/WAD/master/bin/wad | ruby"
```

**Comment by Manfred** [comment]
We've stopped using WAD because there is now arbitrary directory caching in Travis:

https://docs.travis-ci.com/user/caching/#Arbitrary-directories

I would recommend using that instead. If you do want this changed in WAD for convenience I will gladly merge a pull request.

**Comment by nomadslim** [comment]
@Manfred 
Understood, thanks for the feedback.
I think merging won't be necessary :)
